

// Bỏ phần:
// import GoogleGenerativeAI from "@google/generative-ai";
// const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// Thay toàn bộ "Step 3 Use Gemini AI..." bằng:
const apiKey = process.env.GEMINI_APIKEY; // giống audit.js
if (!apiKey) {
    console.error("GEMINI_APIKEY not found in environment");
    return res.status(500).json({ error: "API key not configured" });
}

const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`;

const prompt = `
Analyze the following website content and extract brand guideline information.
Return ONLY a valid JSON object (no markdown, no code blocks) with this exact structure:

{
  "brandName": "Company/Brand name",
  "industry": "Industry/Sector",
  "targetAudience": "Target audience description",
  "tone": "Communication tone (formal/casual/friendly/professional)",
  "coreValues": ["Value 1", "Value 2", "Value 3"],
  "keywords": ["keyword1", "keyword2", "keyword3"],
  "visualStyle": "Description of visual style",
  "dos": ["Do this", "Do that"],
  "donts": ["Don't do this", "Don't do that"],
  "summary": "Brief brand summary"
}

Website Data:
- Title: ${extractedData.title}
- Meta Description: ${extractedData.metaDescription}
- Main Content: ${extractedData.mainText}
- About Section: ${extractedData.aboutText}
- Key Headings: ${extractedData.headings.join(" | ")} 
`;

const requestBody = {
    contents: [
        {
            parts: [{ text: prompt }]
        }
    ],
    generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 8192,
        responseMimeType: "application/json",
    },
};

console.log("Calling Gemini API for analyze-brand...");
const aiRes = await fetch(geminiUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(requestBody),
});

if (!aiRes.ok) {
    const errorText = await aiRes.text();
    console.error("Gemini API error (analyze-brand):", aiRes.status, errorText);
    return res.status(aiRes.status).json({
        error: "Gemini API error",
        status: aiRes.status,
        details: errorText,
    });
}

const data = await aiRes.json();
const textResult = data.candidates?.[0]?.content?.parts?.[0]?.text;

if (!textResult) {
    console.error("No text result from Gemini (analyze-brand)");
    return res.status(500).json({ error: "No response from AI" });
}

// Clean + parse JSON tương tự audit.js
let brandGuideline = null;
try {
    const cleaned = textResult
        .trim()
        .replace(/```json?/gi, '')
        .replace(/```/g, '')
        .replace(/[\u0000-\u0008\u000B-\u000C\u000E-\u001F]/g, '');
    brandGuideline = JSON.parse(cleaned);
} catch (parseError) {
    console.warn("ANALYZE JSON parse failed at BE:", parseError.message);
    return res.status(500).json({
        error: "Failed to parse AI response",
        details: parseError.message,
        rawResponse: textResult,
    });
}

const responseData = {
    ...brandGuideline,
    sourceUrl: websiteUrl,
    analyzedAt: new Date().toISOString(),
    method: "autogenerated",
    confidence: "medium",
};

console.log("Successfully analyzed brand:", responseData.brandName);
return res.status(200).json({ success: true, data: responseData });
